In [3]:
import tensorflow as tf

In [5]:
aa = tf.random_uniform( (5,5), -1, 1)

In [7]:
with tf.Session() as ss: 
    print(ss.run(aa))

[[ 0.82277822 -0.80370998  0.01206326 -0.4553988  -0.21079254]
 [ 0.60133576  0.64822316 -0.6873138   0.94765449  0.34970856]
 [ 0.90649223  0.5926857   0.94032359  0.18150949  0.47032261]
 [-0.83306837  0.2651248  -0.46285868 -0.1015265   0.60828257]
 [-0.09714937 -0.29015255 -0.22685862  0.11457658 -0.45087409]]


In [13]:
ssint = tf.InteractiveSession()
#ssint.run(aa)

In [14]:
var1 = tf.Variable(initial_value=aa)

In [15]:
#var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32_ref>

In [17]:
init = tf.global_variables_initializer()

In [18]:
init.run()

In [19]:
ssint.run(var1)

array([[-0.29617262,  0.08317232, -0.77107096,  0.33274961, -0.35435987],
       [-0.31830287,  0.81044292, -0.8926692 ,  0.47473669,  0.37966633],
       [-0.06193423, -0.83236289,  0.09392262,  0.38187099, -0.49517369],
       [-0.36764431,  0.0657258 , -0.68843937,  0.6066854 ,  0.42748022],
       [ 0.07835078,  0.7302773 , -0.39750099,  0.18481541, -0.37554431]], dtype=float32)

In [20]:
var1.eval()

array([[-0.29617262,  0.08317232, -0.77107096,  0.33274961, -0.35435987],
       [-0.31830287,  0.81044292, -0.8926692 ,  0.47473669,  0.37966633],
       [-0.06193423, -0.83236289,  0.09392262,  0.38187099, -0.49517369],
       [-0.36764431,  0.0657258 , -0.68843937,  0.6066854 ,  0.42748022],
       [ 0.07835078,  0.7302773 , -0.39750099,  0.18481541, -0.37554431]], dtype=float32)

# Contenedores

Los contenedores deben tener definido el tipo de dato que van a contener

In [22]:
p1 = tf.placeholder( tf.float64 )

In [24]:
p2 = tf.placeholder( tf.float64 )

In [ ]:
p3 = tf.placeholder( tf.int32 )

In [26]:
p4 = tf.placeholder( tf.float64, shape=(None, 5) )

In [27]:
p4

<tf.Tensor 'Placeholder_5:0' shape=(?, 5) dtype=float64>

In [45]:
n1 = tf.constant([[1,2] , [3, 4] ])

In [46]:
n2 = tf.constant([ [1,1] , [2,1]])

In [47]:
suma = n1*n2

In [48]:
suma

<tf.Tensor 'mul_1:0' shape=(2, 2) dtype=int32>

In [51]:
with tf.Session() as sss:
    print( sss.run(suma))

[[1 2]
 [6 4]]


In [63]:
gg = tf.Graph()

In [64]:
gg

In [65]:
gg1 = tf.get_default_graph()

In [66]:
gg1

In [67]:
gg.as_default()

In [69]:
gg2 = tf.get_default_graph()

In [77]:
with gg.as_default():
    print(gg is tf.get_default_graph())
    print(gg)


True


In [79]:
print(tf.get_default_graph() )

In [80]:
print( gg is tf.get_default_graph() )

False


# 1 neurona

In [82]:
import numpy as np

In [109]:
np.random.seed(22)

In [115]:
tf.set_random_seed(22)

In [110]:
r1 = np.random.uniform( 0, 100, (5,5) )

In [111]:
r1

array([[ 20.84605374,  48.16810618,  42.05380353,  85.91819985,
         17.11615536],
       [ 33.88639606,  27.05328333,  69.10413504,  22.04045166,
         81.19509205],
       [  1.05268743,  56.12036967,  81.37261874,  74.51002961,
         18.91113553],
       [  0.61408663,  77.20438714,  95.78321681,  70.19378841,
         29.75782669],
       [ 76.7992742 ,  68.82183249,  38.71834804,  61.52058251,
         42.75552398]])

In [92]:
r2 = np.random.uniform( 0, 100, (5,1) )
r2

array([[ 82.85403649],
       [ 74.4564463 ],
       [ 17.75370379],
       [ 85.84531959],
       [  0.55124119]])

In [116]:
aa = tf.random_uniform( (5,5), 0, 100 )

In [117]:
ssint.run(aa)

array([[  4.38404083,  38.09778595,  49.86969376,  76.48339081,
         80.31194305],
       [ 24.24334335,  98.69680786,  69.0124054 ,  25.00960922,
         50.97440338],
       [ 28.75022888,  29.56454849,  29.1708107 ,  25.76399994,
         92.30853271],
       [ 12.30007362,  78.92205811,  29.92714691,  36.45757294,
          5.52139282],
       [ 81.50878143,  41.099823  ,  75.39234161,  38.81312561,
         16.57532501]], dtype=float32)

# red

In [118]:
caracteristicas  =10 

In [119]:
num_neuronas = 3 

In [120]:
x = tf.placeholder(tf.float32, (None, caracteristicas ))

In [121]:
bias = tf.Variable ( tf.zeros( [num_neuronas] )) 

In [123]:
W = tf.Variable( tf.random_normal( [caracteristicas, num_neuronas ]) )

In [125]:
x

<tf.Tensor 'Placeholder_6:0' shape=(?, 10) dtype=float32>

In [127]:
bias 

<tf.Variable 'Variable_1:0' shape=(3,) dtype=float32_ref>

In [129]:
W  

<tf.Variable 'Variable_3:0' shape=(10, 3) dtype=float32_ref>

In [130]:
xw = tf.matmul( x , W)

In [131]:
v = tf.add(xw, bias )

In [132]:
xw

<tf.Tensor 'MatMul:0' shape=(?, 3) dtype=float32>

In [133]:
v

<tf.Tensor 'Add:0' shape=(?, 3) dtype=float32>

In [136]:
zz = tf.sigmoid(v)
zz

<tf.Tensor 'Sigmoid_2:0' shape=(?, 3) dtype=float32>

In [137]:
init = tf.global_variables_initializer()

In [138]:
init.run()

In [139]:
with tf.Session() as ssss:
    ssss.run(init)
    salida = ssss.run(zz, feed_dict={ x : np.random.random( [1, caracteristicas])   })

In [140]:
print(salida)

[[ 0.33083776  0.80831188  0.45786941]]
