In [2]:
import tensorflow as tf

In [4]:
ver = tf.__version__

In [5]:
ver


'1.3.0'

In [8]:
print( tf.__version__)

1.3.0


In [10]:
mensaje = tf.constant('Hola mundo')

In [12]:
mensaje

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [13]:
mensaje2 = tf.constant('Hola 2 mundo ')

In [14]:
print(mensaje2)

Tensor("Const_2:0", shape=(), dtype=string)


In [15]:
mx = tf.constant('Hola 3 mundo ')
mx

<tf.Tensor 'Const_3:0' shape=() dtype=string>

In [20]:
with tf.Session() as sss: 
    print(sss.run(mx + mensaje+ mensaje2))

b'Hola 3 mundoHola mundoHola 2 mundo'


In [22]:
type(mx)

tensorflow.python.framework.ops.Tensor

In [28]:
coseno = tf.cos(0.0)

In [30]:
with tf.Session() as sss: 
    print(sss.run(coseno))

1.0


In [39]:
objetos = [mensaje, mensaje2, mx, coseno]

# Sesion interactiva

In [40]:
sess = tf.InteractiveSession()

In [43]:
for ob in objetos:
    print(sess.run( ob ))
    print(ob)

b'Hola mundo'
Tensor("Const_1:0", shape=(), dtype=string)
b'Hola 2 mundo'
Tensor("Const_2:0", shape=(), dtype=string)
b'Hola 3 mundo'
Tensor("Const_3:0", shape=(), dtype=string)
1.0
Tensor("Cos_5:0", shape=(), dtype=float32)


In [47]:
sess.run(coseno)

1.0

In [53]:
r = mensaje + mensaje2
r

<tf.Tensor 'add_4:0' shape=() dtype=string>

In [49]:
sess.run(r)

b'Hola mundoHola 2 mundo'

In [50]:
a = tf.constant(22)

In [51]:
b = tf.constant(23)

In [52]:
rr = a +b
rr

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [55]:
sess.run(rr)

45

In [56]:
type(rr)

tensorflow.python.framework.ops.Tensor

# operaciones con vectores / matrices

In [59]:
g = tf.constant(5)

In [61]:
h = tf.fill((4,5), 9)

In [63]:
sess.run(h)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]], dtype=int32)

In [67]:
h = tf.zeros((4,5))
sess.run(h)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [74]:
i = tf.eye(5)
sess.run(i)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]], dtype=float32)

In [77]:
j = tf.ones((4,5))
sess.run(j)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [79]:
almacen = [g,h,i,j]

In [85]:
for al in almacen:
    print(sess.run(al))
    print('\n')


5


[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]




In [86]:
k = tf.matmul(j, i)

In [88]:
sess.run(k)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [99]:
p = tf.constant([[1.0,2,3,4,5], 
                [1,2,3,4,5], 
                [1,2,3,4,5], 
                [1,2,3,4,5], 
                [9,8,7,6,5]])

In [100]:
sess.run(p)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 9.,  8.,  7.,  6.,  5.]], dtype=float32)

In [104]:
q = tf.matmul( p,p)

In [106]:
sess.run(q)

array([[  55.,   60.,   65.,   70.,   75.],
       [  55.,   60.,   65.,   70.,   75.],
       [  55.,   60.,   65.,   70.,   75.],
       [  55.,   60.,   65.,   70.,   75.],
       [  75.,  100.,  125.,  150.,  175.]], dtype=float32)

In [108]:
q = tf.matmul( p,p)

In [110]:
r = tf.matmul(p,q)

In [113]:
q


<tf.Tensor 'MatMul_7:0' shape=(5, 5) dtype=float32>

In [118]:
r

<tf.Tensor 'MatMul_9:0' shape=(5, 5) dtype=float32>

In [119]:
sess.run(r)

array([[  925.,  1100.,  1275.,  1450.,  1625.],
       [  925.,  1100.,  1275.,  1450.,  1625.],
       [  925.,  1100.,  1275.,  1450.,  1625.],
       [  925.,  1100.,  1275.,  1450.,  1625.],
       [ 2025.,  2300.,  2575.,  2850.,  3125.]], dtype=float32)

# otro ejemplo de multiplicacion de matrices

In [123]:
aa = tf.constant( [ [1, 2 ] , [3,2], [1 ,0]])
aa.get_shape()

TensorShape([Dimension(3), Dimension(2)])

In [125]:
bb = tf.constant( [ [1], [2] ] )

In [127]:
cc = tf.matmul(aa, bb)

In [130]:
cc.get_shape()

TensorShape([Dimension(3), Dimension(1)])

In [133]:
sess.run(cc)

array([[5],
       [7],
       [1]], dtype=int32)

In [135]:
dd = [aa, bb, cc]

In [142]:
for ee in dd:
    #print(sess.run(ee) )
    print(ee.eval() )
    
    print('\n')

[[1 2]
 [3 2]
 [1 0]]


[[1]
 [2]]


[[5]
 [7]
 [1]]




In [143]:
aa.eval()

array([[1, 2],
       [3, 2],
       [1, 0]], dtype=int32)